wandb_params:
    project: "GreyBoxDPTOptimizer"
    group: "markoviann"
    name: null
    entity: null
    save_dir: "../GreyBoxDPTOptimizerData/"

model_params:
    num_states: 1
    num_actions: 16
    hidden_dim: 128
    num_layers: 4
    num_heads: 4
    seq_len: 50
    attention_dropout: 0.5
    residual_dropout: 0.1
    embedding_dropout: 0.3
    normalize_qk: False
    pre_norm: True
    state_rnn_embedding: 1
    full_sequence: false

optimizer_params:
    lr: 0.0005
    weight_decay: 0.0001
    betas: [0.9, 0.999]

with_scheduler: false
scheduler_params:
    warmup_epochs: 2

# temperature: 100.0
# do_samples: true
label_smoothing: 0.0
precision: "16-mixed"
max_epochs: 300
log_every_n_steps: 1
seed: 42
# clip_grad: null

train_histories_path: "../GreyBoxDPTOptimizerData/trajectories"
val_histories_path: "../GreyBoxDPTOptimizerData/trajectories_test"
batch_size: 512
num_workers: 8