wandb_params:
    project: "DPT_2"
    group: "quadratic"
    name: null
    entity: null
    save_dir: "../results/"

model_params:
    seq_len: 3
    input_dim: 1
    hidden_dim: 16
    output_dim: 1
    num_layers: 4
    num_heads: 4
    attention_dropout: 0 #0.5
    residual_dropout: 0
    embedding_dropout: 0 #0.3

optimizer_params:
    lr: 0.001
    weight_decay: 0.0001
    betas: [0.9, 0.999]

with_scheduler: false
scheduler_params:
    warmup_epochs: 2

label_smoothing: 0.1
precision: 32
max_epochs: 200
log_every_n_steps: 1
seed: 42
# clip_grad: null
# temperature: 1
# do_samples: true

n_problems: 5000

batch_size: 512
num_workers: 16

problem: "ContinuousQuadratic"
problem_params:
    d: 1
    n: 1
