wandb_params:
    project: "GreyBoxDPTOptimizer_2"
    group: "markoviann"
    name: null
    entity: null
    save_dir: "../GreyBoxDPTOptimizerData/"

model_params:
    num_actions: 1024
    hidden_dim: 128
    num_layers: 4
    num_heads: 4
    seq_len: 100
    attention_dropout: 0 #0.5
    residual_dropout: 0 #0.1
    embedding_dropout: 0 #0.3
    pre_norm: True

optimizer_params:
    lr: 0.001
    weight_decay: 0.0001
    betas: [0.9, 0.999]

remove_target: true
ordered: true

with_scheduler: false
scheduler_params:
    warmup_epochs: 2

loss: "dynamic"
label_smoothing: 0.1
precision: "16-mixed"
max_epochs: 500
log_every_n_steps: 1
seed: 42
# clip_grad: null
# temperature: 1
# do_samples: true

n_problems: 1000

batch_size: 512
num_workers: 8

problem: "SimpleQuadratic"
# problem: "Quadratic"
problem_params:
    d: 1
    n: 1024
