wandb_params:
    project: "GreyBoxDPTOptimizer"
    group: "markoviann"
    name: null
    entity: null
    save_dir: "../GreyBoxDPTOptimizerData/"

model_params:
    num_states: 1
    num_actions: 1024
    hidden_dim: 64
    num_layers: 4
    num_heads: 4
    seq_len: 100
    attention_dropout: 0.5
    residual_dropout: 0.1
    embedding_dropout: 0.3
    normalize_qk: False
    pre_norm: True
    state_rnn_embedding: 1
    full_sequence: false

optimizer_params:
    lr: 0.0005
    weight_decay: 0.0001
    betas: [0.9, 0.999]

with_scheduler: false
scheduler_params:
    warmup_epochs: 2

# temperature: 100.0
# do_samples: true
label_smoothing: 0.0
precision: "16-mixed"
max_epochs: 1000
log_every_n_steps: 1
seed: 42
# clip_grad: null

trajectories_path: "../GreyBoxDPTOptimizerData/trajectories/Quadratic_d_1_n_1024"
# results_path: "../GreyBoxDPTOptimizerData/results_test"
n_problems: 1000
ordered: false

batch_size: 512
num_workers: 8

problem: "Quadratic"
problem_params:
    # d: 10
    # n: 2
    d: 1
    n: 1024