attention_dropout: 0.5
batch_size: 16
betas:
- 0.9
- 0.999
checkpoints_path: solvers/dpt/checkpoints
clip_grad: null
data_seed: 0
embedding_dropout: 0.3
entity: null
eval_episodes: 200
eval_every: 10000
eval_seed: 42
eval_test_goals: 50
eval_train_goals: 20
group: markoviann
hidden_dim: 512
label_smoothing: 0.0
learning_histories_path: solvers/dpt/trajectories
learning_rate: 0.0003
name: null
normalize_qk: false
num_actions: 16
num_heads: 4
num_layers: 4
num_states: 1
num_workers: 0
pre_norm: true
project: GreyBoxDPT
residual_dropout: 0.1
rnn_dropout: 0.0
rnn_hidden: 1
seq_len: 50
subsample: 1
train_seed: 42
update_steps: 50
warmup_ratio: 0.05
weight_decay: 0.0001
with_key_indicator: true
with_prior: false
with_scheduler: false
