wandb_params:
    project: "DPT_3"
    group: "QUBO"
    name: null
    entity: null
    save_dir: "../results"

model_params:
    state_dim: 11
    action_dim: 11
    seq_len: 100
    hidden_dim: 32
    num_layers: 4
    num_heads: 4
    attention_dropout: 0.0 #0.5
    residual_dropout: 0.0 # 0.1
    embedding_dropout: 0.0 #0.3
    # with_alibi: true

optimizer_params:
    lr: 0.0005 # 0.005
    weight_decay: 0.0001 # 5.e-5
    # eps: 1.e-7
    # warmup_steps: 250
    betas: [0.9, 0.999] # [0.9, 0.99]

problem_params:
    d: 10
    n: 2

with_scheduler: false
scheduler_params:
    warmup_epochs: 5

parallel: true
data_path: "data/normal_10"

action: "bitflip"
target_action: "gt"
ad_ratio: 0.0
trajectories_path: "results/normal_10"

label_smoothing: 0.0 #1
precision: bf16-mixed
max_epochs: 100
log_every_n_steps: 1
seed: 42
# clip_grad: null

do_sample: false
temperature: 1
warmup_steps: 0
online_steps: 50

batch_size: 512
num_workers: 0 # 16

strategy: ddp
exclude_problems: [
    'Normal(5, 1)',
]