problem_list:
  - problem: QUBO
    kwargs: {}
  - problem: Knapsack
    kwargs: {}
  - problem: MaxCut
    kwargs: {}
  - problem: WMaxCut
    kwargs: {}
  - problem: MVC
    kwargs: {}
  - problem: WMVC
    kwargs: {}
  - problem: NumberPartitioning
    kwargs: {}
  - problem: GraphColoring
    kwargs: {}
  - problem: QAP
    kwargs: {}
  - problem: MaxClique
    kwargs: {}

solver: 
  name: RandomSearch
  budget: 1000
  n_runs: 3
  full_info: False