problem_list:
  - problem: GraphColoring
    kwargs: {}
  - problem: Ising
    kwargs: {}
  - problem: Knapsack
    kwargs: {}
  - problem: Max2Sat
    kwargs: {}
  - problem: MaxClique
    kwargs: {}
  - problem: MaxCut
    kwargs: {}
  - problem: MVC
    kwargs: {}
  - problem: NumberPartitioning
    kwargs: {}
  - problem: QAP
    kwargs: {}
  - problem: QUBO
    kwargs: {}
  - problem: SetPack
    kwargs: {}
  - problem: SPP
    kwargs: {}
  - problem: WMaxCut
    kwargs: {}
  - problem: WMVC
    kwargs: {}